server:
  port: 9095

spring:
  cloud:
    config:
      enabled: false
  application:
    name: auth-service

app:
  config:
    keycloak:
      auth-url: http://localhost:28080/auth/realms/micro-dev/protocol/openid-connect/token
      logout-url: http://localhost:28080/auth/realms/micro-dev/protocol/openid-connect/logout
      realm: micro-dev
      client-id: micro-dev-client
      client-secret: 67b306ee-ea01-4d93-b4e0-f94675760246

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
