version: '3.8'
services:
  api-gateway:
    image: api-gateway:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - '9099:9099'
    networks:
      - banco

  auth-service:
    image: auth-service:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - '9095:9095'
    networks:
      - banco

  customer-core:
    image: customer-core:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - '8083:8083'
    networks:
      - banco

  customer-service:
    image: customer-service:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - '8082:8082'
    networks:
      - banco

  auditor:
    image: auditor:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - '9097:9097'
    networks:
      - banco

  cloud-config-server:
    image: cloud-config-server:0.0.1-SNAPSHOT
    ports:
      - '8888:8888'
    networks:
        - banco

  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - cloud-config-server
    ports:
      - '8761:8761'
    networks:
        - banco

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - banco

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - banco

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - banco

  keycloak:
    container_name: local_keycloak
    environment:
       DB_VENDOR: h2
       KEYCLOAK_USER: admin
       KEYCLOAK_PASSWORD: admin
       KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    image: jboss/keycloak:16.1.1
    ports:
      - "28080:8080"
    networks:
      - banco

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - banco

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    networks:
      - banco

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - "3000:3000" # access grafana url
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
    networks:
      - banco

networks:
  banco:
    name: banco
