version: '3.8'
services:
  api-gateway:
    image: api-gateway:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - 9099:9099
    networks:
      - banco

  auth-service:
    image: auth-service:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - 9095:9095
    networks:
      - banco

  customer-core:
    image: customer-core:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - 8083:8083
    networks:
      - banco

  customer-service:
    image: customer-service:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - eureka-server
    ports:
      - 8082:8082
    networks:
      - banco

  cloud-config-server:
    image: cloud-config-server:0.0.1-SNAPSHOT
    ports:
      - 8888:8888
    networks:
        - banco

  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - cloud-config-server
    ports:
      - 8761:8761
    networks:
        - banco

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - banco

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - banco

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - banco

  keycloak:
    container_name: local_keycloak
    environment:
       KEYCLOAK_USER: admin
       KEYCLOAK_PASSWORD: admin
       KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    image: jboss/keycloak:16.1.1
    ports:
      - "28080:8080"
    restart: unless-stopped
    networks:
      - banco

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - banco

networks:
  banco:
    name: banco
